name: fastai
channels:
- soumith
- defaults
dependencies:
- bleach
- certifi
- cffi
- cycler
- dbus
- decorator
- entrypoints
- expat
- fontconfig
- freetype
- glib
- gst-plugins-base
- gstreamer
- html5lib
- icu
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jbig
- jedi
- jinja2
- jpeg
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- libffi
- libgcc
- libgfortran
- libiconv
- libpng
- libsodium
- libtiff
- libxcb
- libxml2
- markupsafe
- matplotlib
- mistune
- mkl
- nbconvert
- nbformat
- notebook
- numpy
- olefile
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pickleshare
- pillow
- pip
- prompt_toolkit
- ptyprocess
- pycparser
- pygments
- pyparsing
- pyqt
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- readline
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- terminado
- testpath
- tk
- tornado
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- zlib
- cuda80=1.0=0
- pytorch=0.2.0=py36h53baedd_4cu80
- torchvision=0.1.9=py36h7584368_1
- pip:
  - bcolz
  - ipython-genutils
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - opencv-python
  - prompt-toolkit
  - torch==0.2.0.post4


